[workspace]
members = [
    "programs/*"
]
resolver = "2"

[workspace.dependencies]
anchor-lang = "0.31.1"
anchor-spl = "0.31.1"
solana-program = "~1.18.17"

[profile.release]
overflow-checks = true
lto = "fat"
codegen-units = 1